### PR TITLE
Add extra settings to json config files.

### PR DESCRIPTION
**Pull request by jacqueswww**
The tests failed for because the didn't align on the nearcore branch that was being checked out.
I also formatted the json files so it's easier to edit them in the future.

### CODE REVIEW

**Comment by bowenwang1996** [comment]
Looks like we have no space left on the CI machine. @vgrichina @ailisp

**Comment by ailisp** [comment]
@bowenwang1996 This seems to run on a shared runner. I just clean all disk space of our runners yesterday
image

**Comment by ailisp** [comment]
Sorry @jacqueswww for inconvenience. Use only our runners now, should be pass on the next run, please commit something to let ci schedule build in new runners.

**Comment by vgrichina** [comment]
@ailisp looks like build didn't get triggered for new commit

**Pull request merged**
