### PR TITLE
Update to use generic decoder

### PR DESCRIPTION
**Pull request by willemneal**
The newest staging branch for asc uses a generic decode function, which this is updated to use.

### CODE REVIEW

**Comment by vgrichina** [comment]
@willemneal let's merge directly to `master`

which assemblyscript branch is needed for this?

**Comment by willemneal** [comment]
The generic function is in the current near/assemblyscript master, but with the new PR breaks because of the way I had to solve the polymorphism for the decode function.  See: https://github.com/AssemblyScript/assemblyscript/issues/828 

Basically can't have a union type with a reference and a typedarry.  However, I was able to get around this with a generic type with a default.

So in the current [PR:](https://github.com/nearprotocol/assemblyscript/pull/66)  decode is `decode<T, V = Uint8Array>(buf: V): T`, which then can check the instance of `buf` inside the function.  This, however, broke something when you are calling decode on a generic object like in this instance, but the generic decode function is the way to handle this anyway since it does what was done here internally.

**Comment by willemneal** [comment]
@janedegtiareva I changed some internal functions to get the test to build.  I also added some type files so that`encode<T>()` and `decode<T>()` are defined for IDEs.

**Comment by willemneal** [comment]
The failure seems that the gitlab isn't getting the newest version of assemblyscript.  Is there a reason that `yarn.lock` is ignored?

**Comment by DanielRX** [comment]
Can we have a tester function in this?

i.e.
`type StrAlias = string;`
`export function aliased(s: StrAlias): StrAlias {return s; }`
and then a test calling the function, as when we last tried this branch, it did not work to fix this bug

**Comment by willemneal** [comment]
That test is in the assemblyscript repo.

**Comment by willemneal** [comment]
I was waiting to for this to pass CI tests before I updated near-shell to
the new assemblyscript.  In the repo you're testing trying adding
nearprotocol/assemblyscript as a dependency which nearshell should pick up.

**Comment by willemneal** [comment]
Was able to test this locally and I get the following error:
```ts
Running promiseTests
[FAIL] {"balance":0,"storage_usage":0,"return_data":"None","burnt_gas":14639,"used_gas":14889,"logs":["LOG: promiseTests"]}
{"receipt_indices":[],"receiver_id":"contractNameForPromise","method_name":"methodName","arguments":"","attached_deposit":0,"prepaid_gas":100}
{"receipt_indices":[0],"receiver_id":"contractNameForPromise","method_name":"methodName","arguments":"","attached_deposit":0,"prepaid_gas":100}
WasmerCallError("Returning joint promise is currently prohibited.")
```

**Comment by willemneal** [comment]
Okay so assemblyscript compilation and testing is fixed, but nearcore is failing the promise test.  @janedegtiareva What seems to be the issue with it?

**Pull request merged**
