### PR TITLE
Move away from compiler and create new near compiler frontend

### PR DESCRIPTION
**Pull request by willemneal**
Now there is a `near-asc` binary that will add the files needed for bindings.   Also `index.js` now exports the an `asc.main` function and a `compile` function similar to the one exported by near shell.  This allows a file like the `tests/asconfig.js` which can be used as a simple entry.

### CODE REVIEW

**Comment by ailisp** [comment]
New ci setting looks great! Was planning to work on it (replace npm with yarn, make it top level runnable as commented by @vgrichina but you already did more than that :+1: ). Seems the failed test is missing webpack?

**Comment by vgrichina** [comment]
> New ci setting looks great! Was planning to work on it (replace npm with yarn, make it top level runnable as commented by @vgrichina but you already did more than that 👍 ). Seems the failed test is missing webpack?

`yarn test` has been added earlier https://github.com/nearprotocol/near-runtime-ts/commit/9381e70a9cc1239f1c6dee4c3c4a48ac41b793ab

**Comment by vgrichina** [comment]
meta: I suggest this instead should be separate  package (e.g. `near-bindgen-ts`) as generally you can use `near-runtime-ts` without it. Dependency only exists in tests.

**Comment by bowenwang1996** [comment]
I don't see the need to have a separate repo for binding generation. For Rust we don't have a separate repo for runtime. If the concern is that the name of the repo would not represent what it has, we can rename this repo or start a new one with a new name but has both binding generation and runtime library.

**Comment by bowenwang1996** [comment]
@willemneal looks like CI fail because something is not installed properly

**Comment by willemneal** [comment]
@ailisp The issue is that we are still dependent on changes to the compiler.  Currently I was able to fix the floating point issue, but it requires making changes the standard library.  I'm going to make a PR to upstream about it, but until then we need it.

But then there is also the case of checking for floating point numbers, which I am also adding to the compiler.

I did, however, clean up our fork to do the bare minimum required changes to the compiler.

**Comment by ailisp** [comment]
> With github actions can CI tests update dependencies in other repos and run tests there? This way we could still have a separate repo for the bindings code but CI would test it in this repo too. Also moving forward gitlab seems too constricting since you have to be a collaborator to have tests run when making a PR.

I think it doesn't support. Also I find it's very rudimentary and does not support cache. @bowenwang1996 suggest travis ci, that may support better integration features.

> @ailisp The issue is that we are still dependent on changes to the compiler. Currently I was able to fix the floating point issue, but it requires making changes the standard library. I'm going to make a PR to upstream about it, but until then we need it.
But then there is also the case of checking for floating point numbers, which I am also adding to the compiler.

I see, a lot of hard work. As a compiler they're so unstable is truly annoying. 

> I did, however, clean up our fork to do the bare minimum required changes to the compiler.

I think you did is the best we can do.

**Comment by janedegtiareva** [comment]
Is this still necessary? @willemneal

**Comment by janedegtiareva** [comment]
ping about this PR. Should we close this now? @willemneal

**Comment by willemneal** [comment]
@janedegtiareva Yep!

**Pull request closed without merging**
